# Example compose config for Storyteller

services:
  web:
    image: registry.gitlab.com/smoores/storyteller:latest # For CUDA, use registry.gitlab.com/smoores/storyteller:cuda-latest
    # Uncomment for CUDA
    volumes:
      # This can be whatever you like; you can even use a
      # named volume rather than a bind mount, though it's easier
      # to inspect the files with a mount.
      # If you're running on macOS or Windows, you may want to
      # consider using a named volume, which will considerably
      # improve filesystem I/O performance. See these VS Code
      # docs for more information:
      # https://code.visualstudio.com/remote/advancedcontainers/improve-performance#_use-a-targeted-named-volume
      - ~/Documents/Storyteller:/data:rw
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Generate a cryptopgraphically secure random string,
      # e.g. with:
      #  openssl rand -base64 32
      - STORYTELLER_SECRET_KEY=/run/secrets/secret_key
      # Uncomment for CUDA
      - STORYTELLER_DEVICE=cuda
    ports:
      - "8001:8001"
    secrets:
      - secret_key
    devices:
      - "/dev/nvidia0:/dev/nvidia0"  # map a specific GPU (for NVIDIA GPUs)
secrets:
  secret_key:
    file: ./STORYTELLER_SECRET_KEY.txt
